# Generated by Django 5.2.7 on 2025-11-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho_total', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('config_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'game_mapa',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('elemento', models.CharField(choices=[('agua', 'Água'), ('fogo', 'Fogo'), ('planta', 'Planta')], db_index=True, max_length=10)),
                ('numero_associado', models.PositiveIntegerField(unique=True)),
                ('sprite_url', models.URLField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'game_pokemon',
                'indexes': [models.Index(fields=['elemento', 'ativo'], name='idx_pokemon_elem_ativo')],
            },
        ),
        migrations.CreateModel(
            name='MapaPosicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('tipo_zona', models.CharField(choices=[('neutra', 'Neutra'), ('bonus', 'Bônus'), ('perda', 'Perda'), ('batalha', 'Batalha'), ('captura', 'Captura')], max_length=15)),
                ('valor_param', models.IntegerField(blank=True, null=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='game.mapa')),
            ],
            options={
                'db_table': 'game_mapa_posicao',
                'indexes': [models.Index(fields=['mapa', 'tipo_zona'], name='idx_mapa_tipozona')],
                'constraints': [models.UniqueConstraint(fields=('mapa', 'posicao'), name='uq_mapa_posicao'), models.CheckConstraint(condition=models.Q(('posicao__gte', 1)), name='ck_posicao_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('em_andamento', 'Em andamento'), ('encerrada', 'Encerrada')], db_index=True, default='em_andamento', max_length=20)),
                ('berries_iniciais', models.PositiveIntegerField(default=100)),
                ('rodada_limite', models.PositiveSmallIntegerField(default=10)),
                ('rodada_atual', models.PositiveSmallIntegerField(default=1)),
                ('posicao_atual', models.PositiveSmallIntegerField(default=1)),
                ('rounds_restantes_captura', models.PositiveSmallIntegerField(default=0)),
                ('resumo_final', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partida', to='game.mapa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
                ('pokemon_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_iniciadas', to='game.pokemon')),
            ],
            options={
                'db_table': 'game_partida',
                'indexes': [models.Index(fields=['user', 'estado'], name='idx_partida_user_estado'), models.Index(fields=['atualizado_em'], name='idx_partida_update')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rodada_atual__gte', 1)), name='ck_rodadaatual_gte_1'), models.CheckConstraint(condition=models.Q(('posicao_atual__gte', 1)), name='ck_posicaoatual_gte_1')],
            },
        ),
    ]
