# Generated by Django 5.2.7 on 2025-11-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveSmallIntegerField()),
                ('escolhas_numeros', models.JSONField(default=list)),
                ('houve_aposta', models.BooleanField(default=False)),
                ('valor_aposta', models.PositiveIntegerField(default=0)),
                ('numero_sorteado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('vitoria', 'Vitoria'), ('derrota', 'Derrota'), ('sem_aposta', 'Sem aposta')], max_length=15, null=True)),
                ('multiplicador_base', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('ajuste_elemental', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('multiplicador_efetivo', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('berries_delta', models.IntegerField(default=0)),
                ('detalhe_elemental', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batalhas', to='game.partida')),
                ('pokemon_adversario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batalhas_como_adversario', to='game.pokemon')),
                ('pokemon_jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batalhas_como_jogador', to='game.pokemon')),
            ],
            options={
                'db_table': 'game_batalha',
                'indexes': [models.Index(fields=['partida', 'rodada'], name='idx_batalha_partida_rodada'), models.Index(fields=['resultado'], name='idx_batalha_resultado')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_aposta__gte', 0)), name='ck_batalha_aposta_gte_0'), models.CheckConstraint(condition=models.Q(('multiplicador_efetivo__gte', 1.0)), name='ck_batalha_multi_min')],
            },
        ),
        migrations.CreateModel(
            name='EventoRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveSmallIntegerField()),
                ('tipo_evento', models.CharField(max_length=30)),
                ('mensagem_usuario', models.CharField(blank=True, max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='game.partida')),
            ],
            options={
                'db_table': 'game_evento_rodada',
                'indexes': [models.Index(fields=['partida', 'rodada'], name='idx_evento_partida_rodada'), models.Index(fields=['partida', 'criado_em'], name='idx_evento_partida_created')],
            },
        ),
    ]
