# Generated by Django 5.2.7 on 2025-11-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_batalha_eventorodada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapaposicao',
            options={'verbose_name': 'Mapa Posição', 'verbose_name_plural': 'Mapa Posições'},
        ),
    ]
