# Generated by Django 5.2.7 on 2025-11-17 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_alter_mapaposicao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('saldo_resultante', models.IntegerField()),
                ('referencia_tipo', models.CharField(blank=True, max_length=30)),
                ('referencia_id', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='game.partida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transacao',
                'indexes': [models.Index(fields=['user', 'criado_em'], name='idx_tx_user_data'), models.Index(fields=['partida', 'criado_em'], name='idx_tx_partida_data'), models.Index(fields=['tipo'], name='idx_tx_tipo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('saldo_resultante__gte', 0)), name='ck_tx_saldo_nao_neg')],
            },
        ),
    ]
